version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - log.Print
      - log.Printf
      - log.Println
      - log.Fatal
      - log.Fatalf
      - log.Fatalln
      
issues:
  max-issues-per-linter: 0
  max-same-issues: 0